#! /usr/bin/env bash

check_and_maybe_fix_patroni() {
  NODE_IP="{{ manager.private_ip }}"
  SERVICE_MANAGER="{{service_manager}}"
  SERVICE_ARGS="{{service_args}}"
  # Check whether patroni is started and has failed to start postgres
  # This may indicate that a (rare) issue has occurred where postgres can't be started properly...
  if $SERVICE_MANAGER $SERVICE_ARGS status patroni && journalctl -u patroni | tail | grep 'Is another postmaster'; then
    echo "$(date): Initial startup is unhealthy, restarting and reinitializing." >> /var/log/cloudify/db_cluster/patroni/startup_check.log
    # ...so we will restart it and then ensure this node is properly repaired.
    $SERVICE_MANAGER $SERVICE_ARGS restart patroni
    cfy_manager dbs reinit -a ${NODE_IP}
  fi
}

while ! journalctl -u patroni | tail | grep 'Future log output will appear'; do
  check_and_maybe_fix_patroni
  if ! journalctl -u patroni | tail | grep 'Future log output will appear'; then
    echo "$(date): Waiting for patroni initial startup to complete healthily..." >> /var/log/cloudify/db_cluster/patroni/startup_check.log
    sleep 3
  fi
done

echo "$(date): Patroni initial startup complete." >> /var/log/cloudify/db_cluster/patroni/startup_check.log
