manager:
  private_ip: 172.17.0.3
  public_ip: 172.17.0.3

rabbitmq:
  cert_path: /tmp/cert.pem
  key_path: /tmp/key.pem
  ca_path: /tmp/ca.pem
  erlang_cookie: cookievalue123
  nodename: rabbit1
  cluster_members:
    rabbit1:
      networks:
        default: 172.17.0.3

services_to_install:
 - queue_service
service_management: supervisord
skip_sudo: true
save_config: false