groups:
  - name: manager
    rules:

      # Recording rules
      - record: manager_healthy
        expr: count by (host, monitor) (sum by (host, monitor) (probe_success) == {{ number_of_http_probes }})
      - record: manager_service_supervisord
        expr: sum by (host, name) (node_supervisord_up{name=~"(cloudify-amqp-postgres|blackbox_exporter|cloudify-composer|cloudify-stage|cloudify-mgmtworker|cloudify-restservice|node_exporter|prometheus|{% if fs_replication %}cloudify-syncthing|{% endif %}cloudify-execution-scheduler|nginx|cloudify-api|cloudify-execution-scheduler)"})
        labels:
          process_manager: supervisord
      - record: manager_service
        expr: manager_service_supervisord
      - record: nginx_up
        expr: manager_service_supervisord{name="nginx"}
      - record: amqp_postgres_up
        expr: manager_service_supervisord{name="cloudify-amqp-postgres"}
      - record: mgmtworker_up
        expr: manager_service_supervisord{name="cloudify-mgmtworker"}
      - record: rest_service_up
        expr: manager_service_supervisord{name="cloudify-restservice"}
      - record: api_service_up
        expr: manager_service_supervisord{name="cloudify-api"}
      - record: execution_scheduler_up
        expr: manager_service_supervisord{name="cloudify-execution-scheduler"}
      - record: console_up
        expr: manager_service_supervisord{name="cloudify-console"}
      - record: composer_up
        expr: manager_service_supervisord{name="cloudify-composer"}

      # Alerting rules
      - alert: manager_down
        expr: probe_success == 0
        for: {{ alert_for }}
        labels:
          severity: critical
        {% raw -%}
        annotations:
          summary: "Manager is down (host {{ $labels.host }})"
          description: "A HTTP probe {{ $labels.instance }} failed on {{ $labels.host }}."
        {%- endraw %}
      - alert: blackbox_exporter_down
        expr: up{job=~"http_200"} == 0
        for: {{ alert_for }}
        labels:
          severity: critical
        {% raw -%}
        annotations:
          summary: "PostgreSQL Exporter is down (host {{ $labels.host }})"
        {%- endraw %}
      - alert: manager_service_down
        expr: manager_service == 0
        for: {{ alert_for }}
        labels:
          severity: warning
        {% raw -%}
        annotations:
          summary: "One of the manager services is down (host {{ $labels.host }})"
          description: "System service {{ $labels.name }} is down on {{ $labels.host }}."
        {%- endraw %}
