groups:
  - name: manager
    rules:

      - alert: manager_down
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        {% raw -%}
        annotations:
          summary: "Manager is down (host {{ $labels.host }})"
          description: "A HTTP probe {{ $labels.instance }} failed on {{ $labels.host }}."
        {%- endraw %}

      - alert: blackbox_exporter_down
        expr: up{job=~"http_(200|401)"} == 0
        for: 1m
        labels:
          severity: critical
        {% raw -%}
        annotations:
          summary: "PostgreSQL Exporter is down (host {{ $labels.host }})"
        {%- endraw %}

      - alert: manager_service_down
        expr: manager_services == 0
        for: 1m
        labels:
          severity: warning
        {% raw -%}
        annotations:
          summary: "One of the manager services is down (host {{ $labels.host }})"
          description: "System service {{ $labels.name }} is down on {{ $labels.host }}."
        {%- endraw %}
