groups:
  - name: {{ name }}
    rules:{% for host in hosts %}
      - alert: {{ name }}_missing
        expr: absent({{ name }}_healthy{host="{{ host }}"})
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "{{ name|capitalize }} is missing on node {{ host }}"

      - alert: prometheus_missing
        expr: absent(up{host="{{ host }}", job="prometheus"})
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Prometheus is missing on node {{ host }}"
{% endfor %}