groups:
  - name: {{ name }}
    rules:

{% for host in hosts %}
      - alert: {{ name }}_missing
        expr: absent({{ name }}_healthy{host="{{ host }}"})
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ name|capitalize }} is missing on node {{ host }}"
{% endfor %}