groups:
  - name: postgresql
    rules:
{% if 'database_service' in services_to_install %}
      - alert: PostgreSQLDown
        expr: pg_up{instance="localhost:{{ prometheus.postgres_exporter.metrics_port }}", job="postgresql"} != 1
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: PostgreSQL database is down
      - alert: PostgresExporterDown
        expr: up{instance="localhost:{{ prometheus.postgres_exporter.metrics_port }}", job="postgresql"} != 1
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: Postgres Exporter is down
{% endif %}
{% if postgresql_server.cluster.nodes|length > 0 %}
{% for host, postgres in postgresql_server.cluster.nodes.items() %}
      - alert: PostgreSQLInClusterDown
        expr: pg_up{instance="{{ postgres.ip }}:53333", job="federate_postgresql"} != 1
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: One of clustered PostgreSQL databases is down
      - alert: PostgresExporterDown
        expr: up{instance="{{ postgres.ip }}:53333", job="federate_postgresql"} != 1
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: Postgres Exporter is down
{% endfor %}
      - alert: PostgreSQLClusterDegraded
        expr: {% for host, postgres in postgresql_server.cluster.nodes.items() %}up{instance="{{ postgres.ip }}:53333", job="federate_postgresql"} != 1 or pg_up{instance="{{ postgres.ip }}:53333", job="federate_postgresql"} != 1{% if not loop.last %} or {% endif %}{% endfor %}
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: PostgreSQL database cluster is degraded
{% endif %}