manager:
  # The manager's private IP address. This is the address which will be used by
  # agent hosts to connect to the Manager's fileserver and message broker.
  private_ip: ''

  # An IP address by which the Manager is accessible externally, such as via the CLI
  # or external clients. If not applicable, provide the same value as "private_ip".
  public_ip: ''

  # Provide an IP or hostname to be used in the local CLI profile on the manager.
  # This might be useful when providing an external certificate.
  cli_local_profile_host_name: 'localhost'

  ######################################################################################
  #
  # As long as you have set the config entries above, you can install the manager with:
  # cfy_manager install
  # The rest of the configuration is only required if you need to change the defaults.
  #
  ######################################################################################

  # This is set by the installer build script. Changing this will not change the edition
  # you are using, but may cause interesting problems.
  premium_edition: set_by_installer_builder

  # Sets whether the first time the manager's VM is booted from a Cloudify manager image
  # its private IP will be propagated to all relevant configuration files.
  set_manager_ip_on_boot: false
  security:
    # When enabled, the external REST communication will be performed over HTTPS
    ssl_enabled: false

    # Username and password of the Cloudify Manager administrator.
    admin_username: admin
    # If admin_password is left blank, a password will be generated for you and provided
    # to you at the end of the install process.
    # IMPORTANT - In case of clustering with an external database, take note of the admin_password
    admin_password: ''

cluster:
  # The cluster's master manager's IP to join to
  # Must be in the same architecture as this manager:
  #   I.E - all-in-one with all-in-one or external db with external db
  # IMPORTANT - Make sure to update the admin_password's value with the correct
  #             admin_password of the master manager
  master_ip: ''

  # The joining node's name
  # In case node_name is left blank, it will be generated
  node_name: ''

  # The joining node's IP to use for cluster communication
  # default: Private IP
  host_ip: ''

manager-ip-setter:
  sources:
    manager_ip_setter_rpm: cloudify-manager-ip-setter-*.rpm

provider_context:
  workflows:
    # Sets the number of times a failed task will be retried on recoverable error.
    task_retries: 60

    # Sets the interval between retry attempts in seconds.
    task_retry_interval: 15

  policy_engine:
    start_timeout: 30

  # An imported URL is prefix-matched against the key in each entry. If a match is found,
  # then the URL prefix is replaced with the value of the corresponding entry.
  # That allows serving YAML files from within the manager, even when the imported URL
  # points to the external network.
  import_resolver:
    parameters:
      rules:
        - {'http://www.getcloudify.org/spec': 'file:///opt/manager/resources/spec'}
        - {'http://cloudify.co/spec': 'file:///opt/manager/resources/spec'}
        - {'https://www.getcloudify.org/spec': 'file:///opt/manager/resources/spec'}
        - {'https://cloudify.co/spec': 'file:///opt/manager/resources/spec'}
      # if this is set to true, the import resolver will try the original,
      # non-resolved URL as well, if the resolved one returns a HTTP error
      fallback: true

agent:
  # A dict of network names and IP addresses of managers and brokers associated with them.
  # By default, there is only a "default" network, with the manager's
  # private IP and broker IPs associated with it. This network can be overwritten.
  # Structure:
  # networks:
  #   <network_name>: 
  #     manager: <manager address or ip>
  #     brokers:
  #       - <broker name or ip1>
  #       ...
  #       - >broker name or ipN>
  #   <network2_name>: ...
  networks: {}
  broker_port: 5671
  min_workers: 2
  max_workers: 5
  # AMQP heartbeat timeout. 0 means no heartbeats
  heartbeat: 30

rabbitmq:
  # Sets the username/password to use for clients such as celery to connect to
  # the rabbitmq broker. It is recommended that you set both the username and
  # password to something reasonably secure.
  username: cloudify
  password: c10udify

  # Sets the File Descriptor limit for the rabbitmq user.
  # Not used if an external endpoint is used.
  fd_limit: 102400
  nodename: cloudify-manager@localhost

  # The hostname or IP address by which RabbitMQ is known to
  # Cloudify Manager's components (REST service and management workers).
  # This setting doesn't affect the hostname/IP by which agents access
  # the manager.
  endpoint_ip: localhost

  sources:
    erlang_rpm_source_url: erlang-21.0.2-1.el7.centos.x86_64.rpm
    socat_rpm_source_url: socat-1.7.3.2-2.el7.x86_64.rpm
    rabbitmq_rpm_source_url: rabbitmq-server-3.7.7-1.el7.noarch.rpm
    cloudify_rabbitmq_package: cloudify-rabbitmq-*.noarch.rpm

  # IP of the management API, should be localhost unless an external rabbitmq
  # is used
  management_endpoint_ip: 'localhost'

  policy_metrics:
    # Sets the number of milliseconds to wait before a message expires
    # in the events queue. Not used if an external endpoint is used.
    events_queue_message_ttl: 60000

    # Sets the number of messages the events queue can hold. Note this is NOT
    # the message byte length! Not used if an external endpoint is used.
    # Note that for each of the queue length limit properties, new messages
    # will be queued in RabbitMQ and old messages will be deleted once the
    # limit is reached! https://www.rabbitmq.com/maxlength.html
    events_queue_length_limit: 1000000

    # Sets the number of milliseconds to wait before a message expires
    # in the logs queue. Not used if an external endpoint is used.
    logs_queue_message_ttl: 60000

    # Sets the number of messages the logs queue can hold. Note this is NOT
    # the message byte length! Not used if an external endpoint is used.
    logs_queue_length_limit: 1000000

postgresql_server:
  sources:
    libxslt_rpm_url: libxslt-1.1.28-5.el7.x86_64.rpm
    ps_libs_rpm_url: postgresql95-libs-9.5.3-2PGDG.rhel7.x86_64.rpm
    ps_rpm_url: postgresql95-9.5.3-2PGDG.rhel7.x86_64.rpm
    ps_contrib_rpm_url: postgresql95-contrib-9.5.3-2PGDG.rhel7.x86_64.rpm
    ps_server_rpm_url: postgresql95-server-9.5.3-2PGDG.rhel7.x86_64.rpm
    ps_devel_rpm_url: postgresql95-devel-9.5.3-2PGDG.rhel7.x86_64.rpm

  # For external postgres installation, set to true
  enable_remote_connections: false
  # Password to set for the postgres user
  # This is only relevant for external postgres installations when you enable
  # remote connections
  postgres_password: ''

  # SSL must be enabled for external databases - provide proper certificates
  ssl_enabled: false

postgresql_client:
  sources:
    ps_libs_rpm_url: postgresql95-libs-9.5.3-2PGDG.rhel7.x86_64.rpm
    ps_rpm_url: postgresql95-9.5.3-2PGDG.rhel7.x86_64.rpm
    psycopg2_rpm_url: python-psycopg2-2.5.1-3.el7.x86_64.rpm

  # Default values for the Postgres DB name, host, username and password
  # For external postgres installation, update accordingly
  host: localhost
  # DB name, user name and password to be created
  # default postgres user is used for database initialization
  db_name: cloudify_db
  username: cloudify
  password: cloudify
  # SSL must be enabled for external databases - provide proper certificates
  ssl_enabled: false

  # Password to use when connecting to the database with the postgres user
  # This is only relevant for external postgres installations when you enable
  # remote connections
  postgres_password: ''

stage:
  # If set to true, Cloudify UI will not be installed
  skip_installation: false
  sources:
    nodejs_source_url: node-v10.15.1-linux-x64.tar.xz
    stage_source_url: cloudify-stage-*.tgz

composer:
  # If set to true, Cloudify Composer will not be installed
  skip_installation: false
  sources:
    composer_source_url: cloudify-blueprint-composer-*.tgz

python:
  # Some plugins installed from sources require compilation - installs a
  # compiler and the python headers to allow that.
  install_python_compilers: false

  # If set to true, python sources (e.g. pip) will be removed when
  # uninstalling the Cloudify Manager. NOTE: only set to true if those
  # dependencies weren't available before Cloudify Manager installation
  remove_on_teardown: false

restservice:
  log:
    # Logging level for the REST service. Defaults to 'INFO', as 'DEBUG' may
    # end up logging sensitive information.
    level: INFO

    # The size, in MB, that the REST service log file may grow to before it's
    # rotated.
    file_size: 100

    # Number of historical log files to keep when rotating the REST service logs.
    files_backup_count: 7

  gunicorn:
    # The number of gunicorn worker processes for handling requests. If the
    # default value (0) is set, then min((2 * cpu_count + 1 processes), max_worker_count)
    # will be used.
    worker_count: 0

    # Maximum number of gunicorn workers (if calculated automatically)
    max_worker_count: 12

    # The maximum number of requests a worker will process before restarting.
    # If this is set to zero then the automatic worker restarts are disabled.
    max_requests: 1000

  ldap:
    # LDAP server, admin username, admin password and domain
    server: ''
    username: ''
    password: ''
    domain: ''

    # True if Active Directory will be used as the LDAP authenticator
    is_active_directory: true

    # Any extra LDAP information (separated by the `;` sign. e.g. a=1;b=2)
    dn_extra: ''

  sources:
    agents_source_url: cloudify-agents-*.rpm
    restservice_source_url: cloudify-rest-service-*.x86_64.rpm
    premium_source_url: cloudify-premium-*.x86_64.rpm

  # Minimum available memory for running list query on Manager host in MB.
  min_available_memory_mb: 100

  # Disables insecure REST endpoints
  insecure_endpoints_disabled: true

  # Port to be used by the REST service
  port: 8100

  # Number of failed logins (bad password) before account lockout
  failed_logins_before_account_lock: 4

  # Account lockout time in minutes. `-1` means no account lockout,
  #  even when `failed_logins_before_account_lock` has a value.
  account_lock_period: -1

  # The default page size for REST queries
  default_page_size: 1000

  # Additional environment variables to add to the REST Service's service
  # file.
  extra_env: {}

nginx:
  # Number of nginx worker processes to have.
  # Specify "auto" to use nginx's recommended configuration of one
  # process per core.
  worker_processes: auto

  # Number of connections that any nginx worker is allowed to carry simultaneously.
  worker_connections: 4096

  # Maximum number of open file descriptors that any nginx process
  # is allowed to have.
  max_open_fds: 102400

  sources:
    nginx_source_url: nginx-1.13.7-1.el7_4.ngx.x86_64.rpm

mgmtworker:
  sources:
    mgmtworker_source_url: cloudify-management-worker-*.x86_64.rpm

  # Sets the logging level to use for the management workers. This affects the
  # logging performed by the manager during the execution of management tasks,
  # such as deployment creation and deployment deletion. NOTE: specifying
  # "debug" will result in considerable amount of logging activity. Consider
  # using "info" (or a more restrictive level) for production environments.
  log_level: INFO

  # Minimum number of worker processes maintained by the management worker.
  min_workers: 2

  # Maximum number of worker processes started by the management worker.
  max_workers: 100

  # Maximum number of manager-side tasks that can be performed concurrently.
  # This is a performance measure to avoid deployments' starvation, in case
  # a rogue deployment takes over all management workers.
  gatekeeper_bucket_size: 25

  # Additional environment variables to add to the management worker's service
  # file.
  extra_env: {}

patch:
  sources:
    patch_source_url: patch-2.7.1-10.el7_5.x86_64.rpm

cli:
  sources:
    cli_source_url: cloudify-cli-*.x86_64.rpm

sanity:
  # If set to true, the sanity blueprint install/uninstall will not be
  # performed during Cloudify Manager installation
  skip_sanity: false
  sources:
    sanity_source_url: cloudify-hello-world-example-*.tar.gz

dev:
  # Constraints (in standard `pip` constraints format) to pass on to `pip`
  # when installing overlays (such as `rest_service_source_url`, `dsl_parser_source_url`
  # and so on). Example:
  # requests==2.13.0
  # requests-toolbelt==0.7.1
  pip_constraints: ''
  sources:
    cloudify_resources_url: ''
    rest_client_source_url: ''
    plugins_common_source_url: ''
    script_plugin_source_url: ''
    agent_source_url: ''
    dsl_parser_source_url: ''


validations:
  # If set to true, install/configuration validations will not be performed
  skip_validations: false

  # These allow to override specific validation values
  # NOTE: We do not recommend changing these values unless you know exactly
  # what you're doing.
  minimum_required_total_physical_memory_in_mb: 3700

  # Minimum required disk space on Manager host in GB.
  minimum_required_available_disk_space_in_gb: 5

  # Python version expected to be found on the machine
  expected_python_version: '2.7'

  # The only Linux distros fully supported, on which a Cloudify Manager can
  # be installed
  supported_distros: ['centos', 'redhat']

  # The supported versions of the above distros
  supported_distro_versions: ['7']

ssl_inputs:
  external_cert_path: ''
  external_key_path: ''
  internal_cert_path: ''
  internal_key_path: ''
  postgresql_server_cert_path: ''
  postgresql_server_key_path: ''
  postgresql_client_cert_path: ''
  postgresql_client_key_path: ''
  ca_cert_path: ''
  ca_key_path: ''
  ca_key_password: ''
  # External CA cert is used to auto-generate the external cert, if the
  # external cert is not provided.
  # The key and the password will not be stored.
  external_ca_cert_path: ''
  external_ca_key_path: ''
  external_ca_key_password: ''
  internal_manager_host: ''

usage_collector:
  collect_cloudify_uptime:
    # True if the uptime collector will be installed
    active: true

    # Sets the interval between running the uptime collector in hours
    interval_in_hours: 4

  collect_cloudify_usage:
    # True if the usage collector will be installed
    active: true

    # Sets the interval between running the usage collector in days
    interval_in_days: 1

flask_security: {}

# list of services - manager_service, queue_service, database_service
#                    will install only these services on this machine
# I.E - all-in-one installation
# services_to_install:
#   - database_service
#   - queue_service
#   - manager_service

services_to_install:
  - 'database_service'
  - 'queue_service'
  - 'manager_service'

unconfigured_install: true
