manager:
  private_ip: CONTAINER_IP
  public_ip: CONTAINER_IP

rabbitmq:
  cert_path: /etc/cloudify/queue_cert.pem
  key_path: /etc/cloudify/queue_key.pem
  ca_path: /etc/cloudify/ca.pem
  erlang_cookie: cookievalue123
  nodename: rabbit1
  cluster_members:
    rabbit1:
      networks:
        default: CONTAINER_IP
    rabbit2:
      networks:
        default: QUEUE2_IP

prometheus:
  cert_path: /etc/cloudify/queue_cert.pem
  key_path: /etc/cloudify/queue_key.pem
  ca_path: /etc/cloudify/ca.pem
  scape_interval: 5s

services_to_install:
 - queue_service
 - monitoring_service
service_management: supervisord
