manager:
  private_ip: CONTAINER_IP
  public_ip: CONTAINER_IP

rabbitmq:
  cert_path: /etc/cloudify/queue_cert.pem
  key_path: /etc/cloudify/queue_key.pem
  erlang_cookie: cookievalue123
  nodename: rabbit2
  ca_path: /etc/cloudify/ca.pem
  cluster_members:
    rabbit1:
      networks:
        default: QUEUE1_IP
    rabbit2:
      networks:
        default: CONTAINER_IP
  join_cluster: rabbit1

services_to_install:
 - queue_service
# - monitoring_service
