apiVersion: v1
kind: Pod
spec:
  containers:
    - name: py36
      image: circleci/python:3.6
      resources:
        requests:
          cpu: 1
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
    - name: py27
      image: circleci/python:2.7
      resources:
        requests:
          cpu: 0.6
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
      env: 
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    - name: python
      image: python:2
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
    - name: rpmbuild
      image: rpmbuild/centos7
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
    - name: awscli
      image: amazon/aws-cli
      command:
      - cat
      tty: true
  nodeSelector:
    instance-type: spot-xlarge