apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.3-4
      resources:
        limits:
          cpu: 0.3
          memory: 256Mi
    - name: py36
      image: python:3.6
      resources:
        requests:
          cpu: 1
          memory: 1.5Gi
        limits:
          cpu: 1
          memory: 1.5Gi
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    - name: awscli
      image: amazon/aws-cli
      command:
      - cat
      tty: true
      resources:
        limits:
          cpu: 0.3
          memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
