manager:
  private_ip: CONTAINER_IP
  public_ip: CONTAINER_IP

postgresql_server:
  enable_remote_connections: true
  ssl_enabled: true
  ssl_client_verification: true
  ssl_only_connections: true

  cert_path: /etc/cloudify/db_cert.pem
  key_path: /etc/cloudify/db_key.pem
  ca_path: /etc/cloudify/ca.pem

  postgres_password: 'somesecretvalue123!'
  cluster:
    nodes:
      db_1:
        ip: DB1_IP
      db_2:
        ip: DB2_IP
      db_3:
        ip: DB3_IP
    etcd:
      cluster_token: 'somesecretvalue123!'
      root_password: 'somesecretvalue123!'
      patroni_password: 'somesecretvalue123!'
    patroni:
      rest_password: 'somesecretvalue123!'
    postgres:
      replicator_password: 'somesecretvalue123!'

prometheus:
  cert_path: /etc/cloudify/db_cert.pem
  key_path: /etc/cloudify/db_key.pem
  ca_path: /etc/cloudify/ca.pem
  postgres_exporter:
    password: ''
    sslmode: require
  scrape_interval: 5s

services_to_install:
- database_service
- monitoring_service
