manager:
  private_ip: '127.0.0.1'
  public_ip: '127.0.0.1'
  hostname: 'localhost'
  cli_local_profile_host_name: 'localhost'
  premium_edition: premium
  security:
    admin_password: 'admin'
    ssl_enabled: false

sanity:
  skip_sanity: true

postgresql_client:
  server_username: postgres

prometheus:
  scrape_interval: 5s

services_to_install:
  - database_service
  - queue_service
  - manager_service
  - monitoring_service

save_config: false

service_management: supervisord
