manager:
  private_ip: '127.0.0.1'
  public_ip: '127.0.0.1'
  hostname: 'localhost'
  cli_local_profile_host_name: 'localhost'
  premium_edition: premium
  set_manager_ip_on_boot: false
  security:
    admin_password: 'admin'

sanity:
  skip_sanity: true

postgresql_client:
  server_username: postgres

prometheus:
  ca_cert: /etc/cloudify/ssl/cloudify_internal_ca_cert.pem

services_to_install:
  - database_service
  - queue_service
  - manager_service
  - prometheus

prometheus:
  ca_cert: /etc/cloudify/ssl/cloudify_internal_ca_cert.pem


save_config: false
