groups:
  - name: manager
    rules:

      - record: manager_healthy
        expr: count by (host) (sum by (host) (probe_success) == 6)

      - record: manager_services_systemd
        expr: sum by (host, name) (node_systemd_unit_state{name=~"(cloudify-amqp-postgres|blackbox_exporter|cloudify-composer|cloudify-stage|haproxy|cloudify-mgmtworker|cloudify-restservice|node_exporter|prometheus|cloudify-syncthing|nginx).service", state="active"})

      - record: manager_services_supervisord
        expr: sum by (host, name) (node_supervisord_up{name=~"(cloudify-amqp-postgres|blackbox_exporter|cloudify-composer|cloudify-stage|haproxy|cloudify-mgmtworker|cloudify-restservice|node_exporter|prometheus|cloudify-syncthing|nginx).service"})

      - record: manager_services
        expr: manager_services_systemd or manager_services_supervisord