groups:
  - name: rabbitmq
    rules:

      - record: rabbitmq_healthy
        expr: sum by (host) (up{job="rabbitmq"}) == 1

      - record: rabbitmq_service_systemd
        expr: sum by (host, name) (node_systemd_unit_state{name=~"(node_exporter|prometheus|cloudify-rabbitmq|nginx).service", state="active"})

      - record: rabbitmq_service_supervisord
        expr: sum by (host, name) (node_supervisord_up{name=~"(node_exporter|prometheus|cloudify-rabbitmq|nginx).service"})

      - record: rabbitmq_service
        expr: rabbitmq_service_systemd or rabbitmq_service_supervisord