modules:
  http_200:
    prober: http
    http:
      tls_config:
        insecure_skip_verify: false
        ca_file: {{ prometheus.ca_cert_path }}
  http_400:
    prober: http
    http:
      valid_status_codes: [400,]
      tls_config:
        insecure_skip_verify: false
        ca_file: {{ prometheus.ca_cert_path }}
