global:
  scrape_interval: {{  prometheus.scrape_interval }}
  evaluation_interval: {{  prometheus.scrape_interval }}

  external_labels:
    monitor: cloudify

{% if 'manager_service' in services_to_install -%}
rule_files:
  - alerts/manager.yml
  - alerts/postgres.yml
  - alerts/rabbitmq.yml
  - alerts/manager_missing.yml
  - alerts/postgres_missing.yml
  - alerts/rabbitmq_missing.yml
{%- endif %}

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /monitoring/metrics
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_prometheus.yml'

  - job_name: 'node'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_node_exporter.yml'

  - job_name: 'http_200'
    metrics_path: /probe
    params:
      module: [http_200]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:{{ prometheus.blackbox_exporter.metrics_port }}  # The blackbox exporter's real hostname:port.
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_http_200_manager.yml'

  - job_name: 'http_401'
    metrics_path: /probe
    params:
      module: [http_401]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:{{ prometheus.blackbox_exporter.metrics_port }}  # The blackbox exporter's real hostname:port.
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_http_401_manager.yml'

  - job_name: 'federate_http_200'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="http_200",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_managers.yml'

  - job_name: 'federate_http_401'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="http_401",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_managers.yml'

  - job_name: 'federate_manager_prometheus'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="prometheus",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_managers.yml'

  - job_name: 'federate_manager_node'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="node",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_managers.yml'

  - job_name: 'rabbitmq'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_rabbit.yml'

  - job_name: 'federate_rabbitmq'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="rabbitmq",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_rabbits.yml'

  - job_name: 'federate_rabbitmq_prometheus'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="prometheus",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_rabbits.yml'

  - job_name: 'federate_rabbitmq_node'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="node",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_rabbits.yml'

  - job_name: 'postgresql'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_postgres.yml'

  - job_name: 'federate_postgresql'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="postgresql",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_postgres.yml'

  - job_name: 'federate_postgresql_prometheus'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="prometheus",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_postgres.yml'

  - job_name: 'federate_postgresql_node'
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /monitoring/federate
    params:
      'match[]':
        - '{job="node",host!="{{ manager.private_ip }}"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_postgres.yml'
