global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: cloudify

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /monitoring/metrics
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_prometheus.yml'

  - job_name: 'node'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_node_exporter.yml'

  - job_name: 'http_200'
    metrics_path: /probe
    params:
      module: [http_200]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:{{ prometheus.blackbox_exporter.metrics_port }}  # The blackbox exporter's real hostname:port.
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_http_200_manager.yml'

  - job_name: 'http_401'
    metrics_path: /probe
    params:
      module: [http_401]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:{{ prometheus.blackbox_exporter.metrics_port }}  # The blackbox exporter's real hostname:port.
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_http_401_manager.yml'

  - job_name: 'federate_http_200'
    scrape_interval: 15s
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /probe/blackbox
    params:
      'match[]':
        - '{job="http_200"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_managers.yml'

  - job_name: 'federate_http_401'
    scrape_interval: 15s
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /probe/blackbox
    params:
      'match[]':
        - '{job="http_401"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_managers.yml'

  - job_name: 'federate_manager_node'
    scrape_interval: 15s
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /metrics/node
    params:
      'match[]':
        - '{job="node"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_managers.yml'

  - job_name: 'rabbitmq'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_rabbit.yml'

  - job_name: 'federate_rabbitmq'
    scrape_interval: 15s
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /metrics/rabbitmq
    params:
      'match[]':
        - '{job="rabbitmq"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_rabbits.yml'

  - job_name: 'federate_rabbitmq_node'
    scrape_interval: 15s
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /metrics/node
    params:
      'match[]':
        - '{job="node"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_rabbits.yml'

  - job_name: 'postgresql'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/local_postgres.yml'

  - job_name: 'federate_postgresql'
    scrape_interval: 15s
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /metrics/postgres
    params:
      'match[]':
        - '{job="postgresql"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_postgres.yml'

  - job_name: 'federate_postgresql_node'
    scrape_interval: 15s
    honor_labels: true
    scheme: 'https'
    tls_config:
      ca_file: {{ prometheus.ca_path }}
    basic_auth:
      username: {{ prometheus.credentials.username }}
      password: {{ prometheus.credentials.password }}
    metrics_path: /metrics/node
    params:
      'match[]':
        - '{job="node"}'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/other_postgres.yml'
