#! /opt/manager/env/bin/python
import os

from sqlalchemy import select

from manager_rest.flask_utils import setup_flask_app
from manager_rest.storage import models, db

os.environ["MANAGER_REST_CONFIG_PATH"] = "/opt/manager/cloudify-rest.conf"
os.environ["MANAGER_REST_SECURITY_CONFIG_PATH"] = \
    "/opt/manager/rest-security.conf"

dep_table = models.Deployment.__table__
exc_table = models.Execution.__table__


def _set_latest_executions(db):
    """Set .latest_execution for all deployments

    Find the latest execution based on the created_at field, and set it
    for each deployment.
    """
    upd_query = (
        dep_table.update()
        .values(
            _latest_execution_fk=select([
                exc_table.c._storage_id
            ]).where(
                exc_table.c._deployment_fk == dep_table.c._storage_id
            ).order_by(
                exc_table.c.created_at.desc()
            ).limit(1).scalar_subquery()
        )
    )
    db.session.execute(upd_query)
    db.session.commit()


if __name__ == '__main__':
    print('Updating latest executions for all executions...')
    with setup_flask_app().app_context():
        _set_latest_executions(db)
    print('Updated')
